### ISSUE TITLE
Mac OS Arm64 Unity 2022.3.10f1 doesn't build

### ISSUE THREAD

**Issue by Saurabh7SSR** [rive-app/rive-unity-examples#8]
I can't build any of your scenes, after a basic search of the build error that goes something like:
"cannot build while editor is importing or compiling"
the suggested solution was to remove the editor scripts, if I do that it builds but removes all rive goodness.

I can't install via git with git@github.com:rive-app/rive-unity.git?path=package#v0.1.29
it says 
  Error when executing git command. Host key verification failed.
  fatal: Could not read from remote repository.

  Please make sure you have the correct access rights
  and the repository exists.
  
  So I downloaded the package and installed via adding it locally using package.json file of extracted project folder
  
  After clearing Security from Mac OS setting for rive.dylib the project finally works.

But when I try to build I get the can't build because Using UnityEditor: in scripts mainly because of Rive/Editor script files

**Comment by HayesGordon** [comment]
Hi @Saurabh7SSR 

Can you try adding the rive package from the HTTP URL instead: 
```https://github.com/rive-app/rive-unity.git?path=package#v0.1.29```

If that doesn't work can you confirm if you can git clone the rive-unity project. In a terminal run:
```git clone git@github.com:rive-app/rive-unity.git```

If you're not able to do that then there may be a problem with your git ssh setup. See:
- https://docs.github.com/en/authentication/connecting-to-github-with-ssh/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent
- https://stackoverflow.com/questions/13363553/git-error-host-key-verification-failed-when-connecting-to-remote-repository

**Comment by Saurabh7SSR** [comment]
let me clarify, I can play rive files in Unity Editor, but when I build the project for Mac from Unity, it fails pointing to mainly Rive package editor files.

**Comment by HayesGordon** [comment]
Hi @Saurabh7SSR, sorry for the delay in this, it was tied into a bigger change. This should now be fixed in the latest release [v0.1.35](https://github.com/rive-app/rive-unity/releases/tag/v0.1.35)

Could you please confirm if it's working for you.

**Comment by Saurabh7SSR** [comment]
Thanks @HayesGordon, I can build the 3d cube scene after fixing a few missing references and deleting rivestatemachine script. 

No problem at all about the delay, been following the progress of vector graphics on GPU compute for years now, I can't believe the stuff you guys are creating!!!
